import Head from 'next/head'
import React from 'react'
import { Details } from '../../../components/Admin/products/Details'

function ProductsDetailsPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Product Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <Details />
        </>
    )
}

export default ProductsDetailsPage