import Head from 'next/head'
import React from 'react'
import ProductsList from '../../../components/Admin/products/ProductsList'
import { withAuth } from '../../../hoc/withAuth'

function ProductsPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Product List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <ProductsList />
        </>
    )
}

export default withAuth(ProductsPage)