import Head from 'next/head'
import React from 'react'
// import { AddCategory } from '../../../components'
import Details from '../../../components/Admin/categories/Details'
import { withAuth } from '../../../hoc/withAuth'

function CategoryDetailsPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Category Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Details />
        </>
    )

}

export default withAuth(CategoryDetailsPage)