import Head from 'next/head'
import React from 'react'
import { Details } from '../../../components/Admin/orders/Details'

function OrderEditPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Order Edit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <Details />
        </>
    )
}

export default OrderEditPage