import Head from 'next/head'
import React from 'react'
import Orders from '../../../components/Admin/orders/Orders'

function OrdersPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Order List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <Orders />
        </>
    )
}

export default OrdersPage