import { OrderList } from '@seventech/admin'
import Head from 'next/head'
import React from 'react'
import { withAuth } from 'src/hoc/withAuth'

function OrdersPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Order List</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <OrderList />
        </>
    )
}

export default withAuth(OrdersPage)