import Head from 'next/head'
import React from 'react'
import {Detail} from '../../components/client/products/Details'
// import { withAuth } from '../../hoc/withAuth'
function ProductDetails() {
    return (
        <>
            <Head>
                <title>SevenTech | Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Detail />
        </>
    )
}

export default ProductDetails