import { ProductDetail } from '@seventech/client'
import Head from 'next/head'
import React from 'react'

function ProductDetailsPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProductDetail />
        </>
    )
}

export default ProductDetailsPage