import Head from 'next/head'
import React from 'react'
import Cart from '../components/Cart'

function CartPage() {
    return (
        <>
            <Head>
                <title>7-Tech | </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Cart />
        </>
    )
}

export default CartPage