import { Cart } from '@seventech/client';
import Head from 'next/head'
import React from 'react'

function CartPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Cart />
        </>
    )
}

export default CartPage;