import Head from 'next/head';
import React from 'react'
import Category from '../components/Categories'

function CategoryPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Categories</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Category />
        </>
    )
}

export default CategoryPage;