import { Checkout } from '@seventech/client';
import Head from 'next/head';
import React from 'react'

function CheckoutPage() {
  return (
    <>
      <Head>
        <title>SevenTech | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Checkout />
    </>
  )
}

export default CheckoutPage;