import Head from 'next/head';
import React from 'react'
import Checkout from '../components/Checkout'

function CheckoutPage() {
  return (
    <>
    <Head>
        <title>7-Tech | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Checkout />
</>
  )
}

export default CheckoutPage;