import Head from 'next/head'
import React from 'react'
import { Detail } from '../components/products/Details'
// import Details from '../components/products/Details'


function DetailsPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Detail />
        </>
    )
}

export default DetailsPage