import { ForgotPass } from '@seventech/ForgotPass';
import Head from 'next/head';
import React from 'react'

function FpassPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Forgot Password</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ForgotPass />
        </>
    )
}

export default FpassPage;
