import Head from 'next/head'
import Home from '../components/client/Home'

export default function HomePage() {
    return (
        <>
            <Head>
                <title>7-Tech | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Home />
        </>
    )
}