import Head from 'next/head'
import { Homes } from '../components/Home'
import { Shop } from '../components/Shop'
import Layout from '../components/layout/Layout'
import Modal from '../components/products/Details'

// import Footer from '../components/shared/Footer'
// import Navbar from '../components/shared/Navbar'
// import Products from '../components/Products'

export default function MainPage() {
  return (
    <>
      <Head>
        <title>7-Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Homes />
        {/* <Shop /> */}
        <Modal />
      </Layout>

    </>
  )
}
