import Head from 'next/head'
import React from 'react';
import { Main } from '../components';

function MainPage() {
  const [intro, setIntro] = React.useState(true)

  return (
    <>
      <Head>
        <title>SevenTech | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main setIntro={setIntro} />
    </>
  )
}

export default MainPage;