import Head from 'next/head'
import Main from '../components/client/Main'

export default function MainPage() {
  return (
    <>
      <Head>
        <title>SevenTech | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  )
}
