import Head from 'next/head';
import React from 'react'
import Login from '../components/Login';

function LoginPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Login />
        </>
    )
}

export default LoginPage;
