import React from 'react'
import Head from 'next/head'
import Products from '../components/products/Products'

function ProductsPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Products />
            {/* <Modal /> */}
        </>
    )
}

export default ProductsPage