import Head from 'next/head'
import React from 'react'

function SettingsPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Settings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>SettingsPage</div>
        </>
    )
}

export default SettingsPage