import Head from 'next/head'
import React from 'react'
import { CartProvider } from 'react-use-cart'
import Shops from '../components/client/Shop'

function ShopPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CartProvider>
                <Shops />
            </CartProvider>
        </>
    )
}

export default ShopPage