import Head from 'next/head'
import React from 'react'
import Shops from '../components/client/Shop'

function ShopPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Shops />
        </>
    )
}

export default ShopPage