import Head from 'next/head'
import React from 'react'
import Signin from '../components/Signin'

function SigninPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Signup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Signin />
        </>
    )
}

export default SigninPage