import { SubscribersDetails } from '@seventech/Admin'
import Head from 'next/head'
import React from 'react'
import { withAuth } from 'src/hoc/withAuth'

function SubscribersEditPage() {
  return (
    <>
      <Head>
        <title>SevenTech | Subscribers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubscribersDetails />
    </>
  )
}

export default withAuth(SubscribersEditPage)