import Head from 'next/head'
import React from 'react'
import Dashboard from '../../components/Admin/Dashboard'
// import Layout from '../../components/layout/Layout'

function AdminPage() {
    return (
        <>
            <Head>
                <title>7-Tech | Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
           <Dashboard />
        </>
    )
}

export default AdminPage