import { Dashboard } from '@seventech/Admin'
import Head from 'next/head'
import React from 'react'
import { withAuth } from '../../hoc/withAuth'

function AdminPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <Dashboard />
        </>
    )
}

export default withAuth(AdminPage)