import { Settings } from '@seventech/Admin'
import Head from 'next/head'
import React from 'react'
import { withAuth } from '../../hoc/withAuth'

function SettingsPage() {
    return (
        <>
            <Head>
                <title>SevenTech | Settings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Settings />
        </>
    )
}

export default withAuth(SettingsPage)